### PR TITLE
Improve performance by curl_multi_…

### PR DESCRIPTION
**Pull request by toto**
This PR changes the APN access to use the [curl_multi](https://curl.haxx.se/libcurl/c/libcurl-multi.html) interfaces.

This allows vapor-apns to use HTTP/2 multiplexing, pipelining as well as the reuse of TCP-connections leading to greatly improved performance (before sending ~2500 messages took >30 minutes, now it's done in 2 min). 

To support this a few changes were done to achieve this:

1. A API change for `VaporAPNS.send(_ message:ApplePushMessage, to token: String)` which is now asynchronous (`send(to:completionHandler:)`) like the multi-token send method already was.
1. To set options for `curl_multi_` the `Ccurl` library needed to be updated. The package is now pointing to a [fork](https://github.com/toto/CCurl) until the changes get merged.
1. The version was bumped 2.2.1 since this changes core API.

Internally GCD is used to synchronize access to shared structures. Performance wise this is a first step. The scheduling and the core loop of `curl_multi_perform/wait` can certainly be improved, but that is beyond the scope of this PR since this is already a significant improvment. It might make sense to let the user configure certain connection behaviour or play around with the settings (e.g. piplining, max concurrent connections, etc.).

### CODE REVIEW

**Comment by grosch** [comment]
What's the status of getting this merged in?

**Comment by toto** [comment]
I think the CI does not pass because the wrong curl version might not be installed. 

Since creating the PR I used this code to deliver pushes to ~10.000 clients. I will double check the ci error though.

**Comment by toto** [comment]
@matthijs2704 any chance on checking the CI?

**Comment by mxcl** [comment]
Any chance of getting a release with this? Anything I can do to help?

**Pull request merged**
