### PR TITLE
Vapor JWT Package upgrade

### PR DESCRIPTION
**Pull request by anthonycastelli**
I've migrated the current `VaporJWT` package to Vapor's `JWT` package. Slight syntax changes. 

Tested and Verified working on Ubuntu 16.10

### CODE REVIEW

**Comment by vzsg** [comment]
Upgrading JWT to 1.0.1 is critical, as previous versions are broken on Swift 3.1 – caused by a crash in the Base64 encoding functions of Foundation.

**Comment by matthijs2704** [comment]
Thanks @vzsg, yeah I've just heard that too. I don't have much time atm due to graduation preperation, so any input is appreciated. Will merge when tests are fixed!

**Comment by vzsg** [comment]
One more thing, `Package.pins` should be added to `.gitignore` too, not just removed from the repo.

**Comment by anthonycastelli** [comment]
Added the *.pins to the gitignore and fixed up the tests. For some reason, the `testEncoding` test fails, even though it shouldn't.

**Comment by matthijs2704** [comment]
I found some time to take a look at this PR myself. It looks like nothing is working properly currently... It seems like the JWT encoding is going wrong. I'm looking for solutions with @siemensikkema

**Comment by anthonycastelli** [comment]
It seems to be working as expected for me. Both JWT and VaporAPNS

**Comment by vzsg** [comment]
What do you mean it's going wrong?

**Comment by mludi** [comment]
It's failing here
```                do {
                    try jwt2.verifySignature(using: ES256(key: publicKey))
                }
                catch {
                    return Result.error(apnsId: message.messageId, deviceToken: deviceToken, error: .invalidSignature)
                }```

```blablatoken with The used signature may be wrong or something went wrong while signing. Double check the signing key and or try again.```

**Comment by matthijs2704** [comment]
@mlundi not only. The library itself doesnt appear to be working either because the token encoding fails

**Comment by matthijs2704** [comment]
Moved to #39

**Pull request closed without merging**
