### PR TITLE
Prepare for Swift 3.1 

### PR DESCRIPTION
**Pull request by matthijs2704**
Change the code so it's Swift 3.1 ready on Linux (remove typealiases and such)

### CODE REVIEW

**Comment by anthonycastelli** [comment]
I'm working towards this now. Didn't realize I submitted a PR. Oops.

**Comment by matthijs2704** [comment]
@anthonycastelli You didn't ;) I saw you forked and I opened it!

**Comment by anthonycastelli** [comment]
Oh haha. I was scratching my head thinking what had happened 😛

**Comment by anthonycastelli** [comment]
Either i'm missing something or Travis just doesn't want to download Swift 3.1. Anyways, I have tested this on Ubuntu 16.10 and it compiles and executes fine.

**Comment by matthijs2704** [comment]
@anthonycastelli the Travis CI still tests using Swift 3.0 so it'll fail ;) Anyways, thanks for your work! :D

**Pull request merged**
